"""Build the RQ 2.1.1 design-contribution tables.

Two tables, deliberately kept separate because they have different standing:

``auth_ladder``   the risk-band to authentication-requirement mapping. This is a
                  *design* artifact -- it is argued from the threat-model
                  literature, not measured. Its content is declared here.

``auth_band_load`` how much friction that ladder imposes, computed from
                  ``results/06_risk_bands.csv``. This is measured, and it is the
                  only part of the design PaySim can quantify.

Keeping the generator honest about which is which is the point: see
``docs/authentication_design_contribution.md`` section D for what is not claimed.

Usage::

    python scripts/report/build_auth_tables.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / "report" / "tables"

LEARNER = "xgboost"

#: The design ladder. Argued in docs/authentication_design_contribution.md B.2
#: from the factor taxonomy in Ali, Dida & Sam (2020). Not measured.
LADDER = [
    ("Low", "allow", "Baseline 2FA: SIM + PIN",
     "--", "--"),
    ("Medium", "monitor",
     "Baseline 2FA, plus out-of-band notification opening a repudiation window",
     "none (detection)", "Account holder can repudiate"),
    ("High", "step\\_up\\_auth",
     "A third factor from the biometric category, bound to the handset",
     "Inherence", "Vishing and SIM swap both fail this"),
    ("Critical", "block",
     "Hold, plus human verification over a channel not tied to the SIM",
     "Out-of-band identity", "SIM swap, agent-side collusion"),
]

LADDER_COLUMNS = ["Band", "Action", "Authentication requirement",
                  "Category added", "Threat addressed"]


def md_table(caption: str, columns: list[str], rows: list[list[str]],
             source: str) -> str:
    head = "| " + " | ".join(columns) + " |"
    rule = "| " + " | ".join("---" for _ in columns) + " |"
    body = "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    return f"**Table: {caption}**\n\n{head}\n{rule}\n{body}\n\n*{source}*\n"


def tex_table(caption: str, label: str, columns: list[str],
              rows: list[list[str]], align: str, source: str) -> str:
    head = " & ".join(columns) + r" \\"
    body = "\n".join(" & ".join(str(c) for c in r) + r" \\" for r in rows)
    return (f"% generated by scripts/report/build_auth_tables.py\n"
            f"% {source}\n"
            f"% do not edit by hand -- rerun the script\n"
            "\\begin{table}[htbp]\n\\centering\n"
            f"\\caption{{{caption}}}\n\\label{{tab:{label}}}\n"
            f"\\begin{{tabular}}{{{align}}}\n\\toprule\n"
            f"{head}\n\\midrule\n{body}\n\\bottomrule\n"
            "\\end{tabular}\n\\end{table}\n")


def write(stem: str, md: str, tex: str) -> None:
    (TABLES / f"{stem}.md").write_text(md, encoding="utf-8")
    (TABLES / f"{stem}.tex").write_text(tex, encoding="utf-8")
    print(f"  wrote report/tables/{stem}.md and .tex")


def build_ladder() -> None:
    caption = ("Risk band to step-up authentication requirement. A design "
               "mapping argued from the threat-model literature, not an "
               "empirical security result.")
    source = ("Design artifact; see docs/authentication_design_contribution.md "
              "section B. Not derived from any experiment.")
    md_rows = [[c.replace("\\_", "_") for c in row] for row in LADDER]
    write("auth_ladder",
          md_table(caption, LADDER_COLUMNS, md_rows, source),
          tex_table(caption, "authladder", LADDER_COLUMNS, list(LADDER),
                    "llp{4.2cm}ll", source))


def build_load() -> None:
    bands = pd.read_csv(ROOT / "results" / "06_risk_bands.csv")
    d = bands[bands.learner == LEARNER].copy()
    d["share_of_fraud"] = d.n_fraud / d.n_fraud.sum()

    rows = [[
        r.band, r.action.replace("_", "\\_"), f"{r.n_transactions:,}",
        f"{100 * r.share:.2f}\\%", f"{r.n_fraud:,}",
        f"{100 * r.share_of_fraud:.2f}\\%", f"{100 * r.fraud_rate:.3f}\\%",
    ] for r in d.itertuples(index=False)]

    columns = ["Band", "Action", "Transactions", "Share of traffic",
               "Fraud", "Share of fraud", "Fraud rate"]
    caption = ("Operational load of the authentication ladder: how much friction "
               "each band imposes and how much fraud it carries. XGBoost at the "
               "frozen rung, test split.")
    source = "Source: results/06_risk_bands.csv"

    md_rows = [[c.replace("\\%", "%").replace("\\_", "_") for c in r]
               for r in rows]
    write("auth_band_load",
          md_table(caption, columns, md_rows, source),
          tex_table(caption, "authbandload", columns, rows, "llrrrrr", source))

    esc = d[d.band.isin(["High", "Critical"])]
    print(f"\n  escalated bands: {100 * esc['share'].sum():.2f}% of traffic "
          f"carrying {100 * esc['share_of_fraud'].sum():.1f}% of fraud")


def main() -> int:
    TABLES.mkdir(parents=True, exist_ok=True)
    build_ladder()
    build_load()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
