"""Build the E6 threshold-divergence table for the report.

Generated from ``results/E6_paired_by_level.csv`` so no number is transcribed by
hand. Emits both the Markdown and LaTeX forms, matching report/tables/ convention.

Usage::

    python scripts/report/build_e6_table.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
TABLES = ROOT / "report" / "tables"

#: Ascending in R. The two levels at the class ratio are kept as separate rows:
#: the whole point of the eighth level is that the training and validation class
#: ratios are not the same number, and the rules agree at both.
LEVEL_ORDER = ["R_x0.015625", "R_x0.0625", "R_x0.25", "val_class_ratio",
               "R_x1", "R_x4", "R_x16", "R_x64"]

LABELS = {
    "R_x0.015625": "$R/64$", "R_x0.0625": "$R/16$", "R_x0.25": "$R/4$",
    "val_class_ratio": "class ratio", "R_x1": "$R$ (frozen)",
    "R_x4": "$4R$", "R_x16": "$16R$", "R_x64": "$64R$",
}

CAPTION = ("Threshold-rule divergence across the evaluation cost ratio. At the "
           "class ratio the ROC-optimal (B) and risk-optimal (C) rules select "
           "an identical threshold in every cell; away from it they separate, "
           "and C never loses. Means over 104 frozen cells.")


def main() -> int:
    wide = pd.read_csv(ROOT / "results" / "E6_paired_by_level.csv")
    cr = float(wide.loc[wide.R_level == "val_class_ratio", "R_eval"].iloc[0])

    g = (wide.assign(lvl=pd.Categorical(wide.R_level, LEVEL_ORDER, ordered=True))
         .groupby("lvl", observed=True)
         .agg(R_eval=("R_eval", "first"),
              identical=("rules_agree", "mean"),
              gap=("threshold_gap", lambda s: float(np.abs(s).mean())),
              ner_b=("test_ner_B", "mean"),
              ner_c=("test_ner_C", "mean"))
         .reset_index())

    columns = ["Level", "$R$", "Same threshold", "Mean $|$gap$|$",
               "NER (B)", "NER (C)"]
    rows = [[LABELS[r.lvl], f"{r.R_eval:,.2f}", f"{100 * r.identical:.0f}\\%",
             f"{r.gap:.4f}", f"{r.ner_b:.4f}", f"{r.ner_c:.4f}"]
            for r in g.itertuples(index=False)]

    source = "Source: results/E6_paired_by_level.csv"
    tex = ("% generated by scripts/report/build_e6_table.py\n"
           f"% {source}\n% do not edit by hand -- rerun the script\n"
           "\\begin{table}[htbp]\n\\centering\n"
           f"\\caption{{{CAPTION}}}\n\\label{{tab:e6divergence}}\n"
           "\\begin{tabular}{lrrrrr}\n\\toprule\n"
           + " & ".join(columns) + " \\\\\n\\midrule\n"
           + "\n".join(" & ".join(r) + " \\\\" for r in rows)
           + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    (TABLES / "E6_divergence.tex").write_text(tex, encoding="utf-8")

    # Pipes would break the Markdown table, so the absolute-value bars go.
    md_cols = [c.replace("$R$", "R").replace("$|$gap$|$", "Mean abs. gap")
               .replace("Mean Mean abs. gap", "Mean abs. gap") for c in columns]
    md_rows = [[c.replace("\\%", "%").replace("$", "") for c in r] for r in rows]
    md = (f"**Table: {CAPTION}**\n\n"
          "| " + " | ".join(md_cols) + " |\n"
          "| " + " | ".join("---" for _ in md_cols) + " |\n"
          + "\n".join("| " + " | ".join(r) + " |" for r in md_rows)
          + f"\n\n*{source}*\n")
    (TABLES / "E6_divergence.md").write_text(md, encoding="utf-8")

    print("  wrote report/tables/E6_divergence.tex and .md")
    at_ratio = g[g.lvl.isin(["val_class_ratio", "R_x1"])].identical
    print(f"  class ratio = {cr:.4f}; "
          f"{100 * at_ratio.min():.0f}% identical at both class-ratio levels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
